### ISSUE TITLE
CHANGELOG.md

### ISSUE THREAD

**Issue by GaryJones** [benhuson/Taxonomy-Images#24]
For the list of changes as shown on GitHub, you might consider a CHANGELOG.md file, in the style of http://keepachangelog.com/ since that adheres to a growing de facto standard. It's a bit more work, but helps avoid updating the readme.md when changes are made. It also makes the readme less intimidating for those who are new to the plugin, and don't care about the changes that have gone on before.

The intentionally uppercase filename is historical, but allows for case-sensitive operating systems to move these types of files to the top. (README.md should also be uppercase for the same reason; readme.txt needs to be lowercase to be recognised by the WPORG repo.)

**Comment by benhuson** [comment]
Thanks Gary. I always wondered why README file names were often in all caps.

**Comment by benhuson** [comment]
Added in https://github.com/benhuson/Taxonomy-Images/commit/1ebd90975fece344350eab9eae4a3ddca1dc14e6
