### ISSUE TITLE
Open Two windows when click on plus(+) button.

### ISSUE THREAD

**Issue by khubbaib** [benhuson/Taxonomy-Images#27]
I am using this plugin since 1 year but now when i click on plus icon to select images its open standard thickbox and when i choose the images and close the box there is another behind it... Please check this and solve in new version...

**Comment by benhuson** [comment]
Please could you let me know what version of WordPress you are using.

Also, is it when you click the + on the admin page listing lots of terms, or after you click in to edit a single term, or both?

Thanks

**Comment by khubbaib** [comment]
Thanks for reply...
WordPress 4.3.1
On both screens

**Comment by benhuson** [comment]
Hmm, I can't recreate this issue.

What browser are you user? Which version?

**Comment by jtyarks** [comment]
@benhuson I've been able to recreate this with the latest version (0.9.1 as of writing) of Taxonomy Images in Chrome with WordPress version 4.3 and 4.4.

I've uploaded a screen recording to show the behavior: http://pelagic-id.com/bugs/taxonomy-images-double-modal.mov

(This video also shows a secondary issue: a user with Administrator access getting a "You don't have permission to attach files to this post" error when uploading to the media-modal, but not through the old media manager. If you'd like a secondary bug report, I'd be happy to file that.)

**Comment by benhuson** [comment]
Thanks @jtyarks,

I've now been able to recreate the issue with the Visual Term Description Editor plugin installed. The pops up both windows for built in and custom taxonomies.

Works fine without that plugin active.  
@khubbaib, are you able to confirm if you are using that plugin, and if not can you try disabling all other plugins and then reactivating them one-by-one see see if it a conflict with another plugin.

@jtyarks I've been unable to recreate the "You don't have permission to attach files to this post" message. Do you get that with all other plugins deactivated or is that just related to the "Visual Term Description Editor" being active too?

Thanks, Ben

**Comment by benhuson** [comment]
@khubbaib, @jtyarks  Please try downloading this version to see if it fixes the double popup issue for you:
https://github.com/benhuson/Taxonomy-Images/tree/double-popup

The links have a 'thick box' class which I think was used for triggering the old-style media modal and that is somehow automatically triggering the old popup too - although not current sure why only when that plug is active.

[This fix](https://github.com/benhuson/Taxonomy-Images/commit/ca9b223c6ad0d6253c6088235af0c3defc1615a8) only adds the 'thick box' class if the new modal is not supported.

**Comment by jtyarks** [comment]
@benhuson Many, many thanks, that did fix the double-popup issue for me. (I obviously can't speak for  @khubbaib).

To keep this bug report focused, I'm opening a new issue for the 'You don't have permission...' message.

**Comment by khubbaib** [comment]
Yes i am using this plugin and let me check the new version if problem solved..

Thanks for your time :+1:

**Comment by benhuson** [comment]
Hopefully fixed in https://github.com/benhuson/Taxonomy-Images/commit/ca9b223c6ad0d6253c6088235af0c3defc1615a8 and release in version 0.9.2

Please open another issue if you still experience issues.
