### ISSUE TITLE
Uploading image to custom taxonomy gives error: 'You don't have permission to attach files to this post'

### ISSUE THREAD

**Issue by jtyarks** [benhuson/Taxonomy-Images#28]
When trying to upload to an image directly to a custom taxonomy term through the media modal, an error appears. ("You don't have permission to attach files to this post")

Notes:
• Does not happen with core taxonomies
• Happens regardless of user role
• Reproducible on WordPress 4.3 and 4.4
• Happens regardless of theme/plugins activated
• Happens regardless of post type said custom taxonomy is attached to (i.e. core or custom)
• Images already uploaded to media library can be added

I've created a vanilla install of WP with a Twenty Sixteen child theme—only customization being the custom taxonomies—and created a video to highlight the issue: http://www.pelagic-id.com/bugs/taxonomy-images-upload-error.mov

The custom taxonomy code is copied directly from [register_taxonomy Codex page](https://codex.wordpress.org/Function_Reference/register_taxonomy). 

I'm attaching the functions.php file in case that brings any issues to light.
[functions.txt](https://github.com/benhuson/Taxonomy-Images/files/59008/functions.txt)

**Comment by benhuson** [comment]
I've not been able to recreate this issue even though it is clearly demonstrated in your video.

Can you try one thing for me...

If you create a new custom term, then refresh the page before trying to upload an image, does that work?

Thanks

**Comment by jtyarks** [comment]
Many thanks for looking into it. I'm afraid creating a new term, refreshing the page, and then uploading image has the same results.

Would you like access to this environment? It's not being used for anything other than tests.

**Comment by benhuson** [comment]
That would be really useful thanks. You can email me at ben@thewhiteroom.net

**Comment by jtyarks** [comment]
@benhuson Credentials have been sent over.

**Comment by benhuson** [comment]
Thanks, I'll try to find time to test

**Comment by clarkewd** [comment]
This issue is also happening for me with a custom post type. I would love to fix this the right way. I am currently working around by commenting out the ajax security functions in `wp-admin/includes/ajax-actions.php` - not ideal but it works for the moment.
![screen region 2016-01-14 at 14 42 35](https://cloud.githubusercontent.com/assets/156377/12335398/1a0cdaee-bacd-11e5-909b-661636d86827.png)

**Comment by jamirmachado** [comment]
Same issue here.

Error occurs when "editor" user role try to upload image.
Admin user is fine.

**Comment by clarkewd** [comment]
doesn't work for me even with the `admin` user - hope we can get a fix soon

**Comment by benhuson** [comment]
Hi all.

Please could you try this version of the plugin with a patch that may fix the post permission issues.
https://github.com/benhuson/Taxonomy-Images/tree/js-post-error

Please clear your browser cache after installing the plugin and let me know if this helps.

Many thanks

Ben

**Comment by jtyarks** [comment]
@benhuson — That fixed the issue I was experiencing, thanks!

**Comment by benhuson** [comment]
Thanks @jtyarks I'll try to get that fix released as soon as I am able.

**Comment by benhuson** [comment]
Merged in https://github.com/benhuson/Taxonomy-Images/commit/bad8860600f76767b08546f6631a354e0fca63f4
